MODULES=(amdgpu nvidia nvidia_modeset nvidia_uvm nvidia_drm)
BINARIES=()
FILES=()
HOOKS=(base systemd autodetect microcode modconf keyboard sd-vconsole block sd-encrypt filesystems fsck apx_native_v3_76a5f5c6d5ce45d8aed464b9924d5824)
COMPRESSION="zstd"
