# APX Hyprland minimal starter v1. Copied once per Environment.
monitor = , preferred, auto, 1

input {
    kb_layout = pt
    follow_mouse = 1

    touchpad {
        natural_scroll = true
        tap-to-click = true
    }
}

general {
    gaps_in = 4
    gaps_out = 8
    border_size = 2
    layout = dwindle
}

decoration {
    rounding = 4

    blur {
        enabled = false
    }

    shadow {
        enabled = false
    }
}

animations {
    enabled = false
}

misc {
    disable_hyprland_logo = true
    force_default_wallpaper = 0
    disable_splash_rendering = true
}

exec-once = /usr/bin/waybar -c /home/apx/.config/waybar/config.json -s /home/apx/.config/waybar/style.css
exec-once = /usr/bin/mako
exec-once = /usr/lib/hyprpolkitagent/hyprpolkitagent
exec-once = /usr/bin/udiskie --automount --no-tray

bind = SUPER, Return, exec, /usr/bin/alacritty
bind = SUPER SHIFT, Return, exec, /usr/bin/alacritty -e /usr/bin/fastfetch
bind = SUPER, D, exec, /usr/bin/rofi -show drun
bind = SUPER, F, exec, /usr/bin/thunar
bind = SUPER, A, exec, /usr/bin/apx-hub --switcher
bind = SUPER, M, exit
bind = SUPER SHIFT, M, exit
